### ISSUE TITLE
in latest npm version, the commands/strikethroughCommand.tsx is named wrong

### ISSUE THREAD

**Issue by blizzardzheng** [andrerpena/react-mde#171]
in react-mde@7.3.0, the file "commands/strikethroughCommand.tsx" has link error with Case problem. it should be named "strikeThroughCommand".

**Comment by blizzardzheng** [comment]
hope to release a new fixed version?

**Comment by andrerpena** [comment]
That is really weird because I cant find this string on the code. I published 7.3.1 to see if it solves the issue

**Comment by andrerpena** [comment]
I will only be able to investigate at night

**Comment by blizzardzheng** [comment]
in 7.3.0 build result:
![image](https://user-images.githubusercontent.com/11224451/56035147-e8c2d300-5d5b-11e9-896d-ca5a3b931f3c.png)
follow above,the filename doesnot match the link in code.
![image](https://user-images.githubusercontent.com/11224451/56035266-46efb600-5d5c-11e9-908b-29157853eeca.png)
then, it still wrong in 7.3.1

**Comment by andrerpena** [comment]
Thanks. I was able to identify the problem thanks to your message. I
basically deleted the lib folder, built again and now it is there. I just
published another patch

**Comment by ericpinet** [comment]
The name is still wrong in 7.3.4. 

I think that file: strike**through**Command.tsx should be named: strike**Through**Command.tsx (with a capital T)

**Comment by lukezavrel** [comment]
It was correctly named in 7.3.2, but with 7.3.4, it is named incorrectly again

**Comment by andrerpena** [comment]
Thanks to @dcrtantuco fixed on #175
